sonar.projectKey=christopheocr_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
sonar.organization=christopheocr

sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test/**

sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8


sonar.test.exclusions=**/*.spec.ts,**/test/**

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test/**,**/docker/**,**/build/**,**/dist/**
