# === Configuration globale ===
sonar.projectKey=christopheocr_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
sonar.organization=christopheocr
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# === Sources à analyser ===
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/docker/**,**/build/**,**/dist/**

# === Backend (Java) ===
sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# === Frontend (Angular) ===
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

# === Tests à exclure ===
sonar.test.exclusions=**/*.spec.ts,**/test/**
